#mango DB base image pulled
FROM mongo:6.0
#Setting up ENV variable
ENV MONGO_INITDB_ROOT_USERNAME=admin \
    MONGO_INITDB_ROOT_PASSWORD=pass123 \
    MONGO_INITDB_DATABASE=practice_db
#Exposing the port
EXPOSE 27017